### ISSUE TITLE
Missing Files

### ISSUE THREAD

**Issue by davidalexander** [alexadark/hydroblok-surf#2]
Hi @alexadark 

I came to this repo via watching your great talk at https://www.youtube.com/watch?v=_uGYDNmr5UM&list=WL&index=6&t=102s&ab_channel=ShiftConference

I'm working through the repo instructions step by step and am stuck because there is no `.env.example` file to copy and no `root.jsx` to edit in the repo. (I have the storybook account and cloned build to use).

Could you assist? Thanks!

**Comment by alexadark** [comment]
Hi David, I just added the  `.example.env file`.
and the `root.jsx` file is inside the app folder, I have corrected the path on the Read Me file.
Happy coding!

**Comment by davidalexander** [comment]
@alexadark Perfect! Thanks
